name: vesper_cuda
channels:
  - nvidia
  - pytorch
  - conda-forge
dependencies:
  - python=3.11
  - pytorch-cuda=11.8
  - pip
  - pytorch=2.0.1
  - mrcfile
  - numba
  - numpy
  - pyFFTW
  - scipy
  - tqdm
  - scikit-learn
  - mkl=2024.0
  - pip:
      - biopython
      - pydssp
      - gemmi
      - numba_progress